package br.com.equivalencia.view;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author aalmeida
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        getContentPane().setBackground(Color.black);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/equivalencia/imagens/icon app.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnUnidades = new javax.swing.JButton();
        btnGrupoEquiv = new javax.swing.JButton();
        btnArea = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnPpc = new javax.swing.JButton();
        btnEquivalencia = new javax.swing.JButton();
        MenPrincipal = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadArea = new javax.swing.JMenuItem();
        menCadCurso = new javax.swing.JMenuItem();
        menCadPPC = new javax.swing.JMenuItem();
        menCadGrupo = new javax.swing.JMenuItem();
        menCadUnidade = new javax.swing.JMenuItem();
        menCadUsuario = new javax.swing.JMenuItem();
        menEquiv = new javax.swing.JMenu();
        menEquivalencia = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menLogout = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menFluxo = new javax.swing.JMenuItem();
        menManual = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIS Equivalência - Senai Vitória - Tela Principal");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        btnUnidades.setBackground(new java.awt.Color(153, 153, 153));
        btnUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/location.png"))); // NOI18N
        btnUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGrupoEquiv.setBackground(new java.awt.Color(153, 153, 153));
        btnGrupoEquiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/grupoEquiva.png"))); // NOI18N
        btnGrupoEquiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnArea.setBackground(new java.awt.Color(153, 153, 153));
        btnArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/area.png"))); // NOI18N
        btnArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCurso.setBackground(new java.awt.Color(153, 153, 153));
        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/formandos.png"))); // NOI18N
        btnCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPpc.setBackground(new java.awt.Color(153, 153, 153));
        btnPpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/certificado.png"))); // NOI18N
        btnPpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEquivalencia.setBackground(new java.awt.Color(153, 153, 153));
        btnEquivalencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/equivalencia.png"))); // NOI18N
        btnEquivalencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        menCad.setText("Cadastro");

        menCadArea.setText("Área Tecnológica");
        menCadArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadAreaActionPerformed(evt);
            }
        });
        menCad.add(menCadArea);

        menCadCurso.setText("Cursos");
        menCad.add(menCadCurso);

        menCadPPC.setText("PPC");
        menCadPPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadPPCActionPerformed(evt);
            }
        });
        menCad.add(menCadPPC);

        menCadGrupo.setText("Grupo Equivâlencia");
        menCadGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadGrupoActionPerformed(evt);
            }
        });
        menCad.add(menCadGrupo);

        menCadUnidade.setText("Unidades Curriculares");
        menCad.add(menCadUnidade);

        menCadUsuario.setText("Usuários");
        menCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuarioActionPerformed(evt);
            }
        });
        menCad.add(menCadUsuario);

        MenPrincipal.add(menCad);

        menEquiv.setText("Equivalência");

        menEquivalencia.setText("Realizar Equivalência");
        menEquiv.add(menEquivalencia);

        MenPrincipal.add(menEquiv);

        menOpc.setText("Opçôes");

        menLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menLogout.setText("Logout");
        menLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLogoutActionPerformed(evt);
            }
        });
        menOpc.add(menLogout);

        menSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menOpc.add(menSair);

        MenPrincipal.add(menOpc);

        jMenu6.setText("Ajuda");

        menFluxo.setText("Fluxo de Processo");
        jMenu6.add(menFluxo);

        menManual.setText("Manual");
        jMenu6.add(menManual);

        MenPrincipal.add(jMenu6);

        setJMenuBar(MenPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadPPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadPPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadPPCActionPerformed

    private void menCadGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadGrupoActionPerformed

    private void menCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadUsuarioActionPerformed

    private void menLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLogoutActionPerformed
        this.dispose();
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        
    }//GEN-LAST:event_menLogoutActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menSairActionPerformed

    private void menCadAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadAreaActionPerformed
        TelaArea area = new TelaArea();
        area.setVisible(true);
    }//GEN-LAST:event_menCadAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenPrincipal;
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnEquivalencia;
    private javax.swing.JButton btnGrupoEquiv;
    private javax.swing.JButton btnPpc;
    private javax.swing.JButton btnUnidades;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadArea;
    private javax.swing.JMenuItem menCadCurso;
    private javax.swing.JMenuItem menCadGrupo;
    private javax.swing.JMenuItem menCadPPC;
    private javax.swing.JMenuItem menCadUnidade;
    private javax.swing.JMenuItem menCadUsuario;
    private javax.swing.JMenu menEquiv;
    private javax.swing.JMenuItem menEquivalencia;
    private javax.swing.JMenuItem menFluxo;
    private javax.swing.JMenuItem menLogout;
    private javax.swing.JMenuItem menManual;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuItem menSair;
    // End of variables declaration//GEN-END:variables
}
